export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PRODUCT_BY_NAME = 'GET_PRODUCT_BY_NAME';
export const GET_PRODUCT_ID = 'GET_PRODUCT_ID';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_ALL_BRANDS = ' GET_ALL_BRANDS';
export const FILTER_PRODUCTS_BY_CATEGORY = 'FILTER_PRODUCTS_BY_CATEGORY';
export const FILTER_PRODUCTS_BY_PRICE = 'FILTER_PRODUCTS_BY_PRICE';
export const FILTER_PRODUCTS_BY_BRANDS = 'FILTER_PRODUCTS_BY_BRANDS';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_BRANDS = 'CREATE_BRANDS';
export const FILTERS_CLEAR = 'FILTERS_CLEAR ';
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REMOVE_CATEGORY ='REMOVE_CATEGORY';
export const REMOVE_BRANDS ='REMOVE_BRANDS';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const EDIT_BRANDS = 'EDIT_BRANDS';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_FROM_DB = 'ADD_TO_CART_FROM_DB';
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
export const DELETE_ITEM_FROM_CART_LOCALSTORAGE = 'DELETE_ITEM_FROM_CART_LOCALSTORAGE'
export const CART_FROM_LOCALSTORAGE_TO_DB = 'CART_FROM_LOCALSTORAGE_TO_DB';
export const CART_FROM_DB_TO_LOCALSTORAGE = 'CART_FROM_DB_TO_LOCALSTORAGE';
export const DELETE_ALL_CART ='DELETE_ALL_CART'; //localstorage
export const CLEAR_CART = 'CLEAR_CART'; // todo
export const GET_PRODUCTS_CART='GET_PRODUCTS_CART';
export const CHANGE_QTY = 'CHANGE_QTY';


export const UPDATE= 'UPDATE';

export const CREATE_USER = 'CREATE_USER';
export const ERROR_LOGIN='ERROR_LOGIN';


export const GET_USERS = 'GET_USERS';
export const UPDATE_USER = "UPDATE_USER";

//REVIEWS
export const CREATE_REVIEWS= 'CREATE_REVIEWS';
export const GET_REVIEWS='GET_REVIEWS'
